### ISSUE TITLE
Human readable names for the methods

### ISSUE THREAD

**Issue by gartz** [amasad/debug_utils#11]
Yeah, when you are in the console, if you want to use the library, you need to come in the docs to see what each method does, because their names doesn't give's you any clue.

Also should be great to have comment inside the function saying what it does, that way if your not sure if using the right one, just type the object.function_name and you can read the comment saying what it will do if you use it. Very convenient.

**Comment by bernhard-hofmann** [comment]
@gartz raised two issues really. One was as per the title, and the other was around documentation of the functions. Can we split the issues so I can try resolve one without the other?

**Comment by gartz** [comment]
I don't think that override `toString()` it's a good idea, however, you can create a prototype method, that allows to get the help, like `explain()`, but this still doesn't solve the lack of documentation, because you need to know what the lib provide to you to can use, and if you're unsure about how to do it, you can use that method to get more details.

**Comment by bernhard-hofmann** [comment]
Agreed, sticking to the original issue - more explanatory names. :)

**Comment by bernhard-hofmann** [comment]
I'm new to this, so don't shoot me please. I think I've created a PR that closes this issue. If I've gone awry please let me know so I can do better next time.

**Comment by amasad** [comment]
Thanks @bernhard-hofmann! The PR is great (the extra whitespace is the only thing that could've been better :P). It's going out with version 0.6 to the chrome store.

I've created issue #14 to track the docs issue.
